/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AdminGatedRouteRouteImport } from './routes/admin/_gated/route'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AdminGatedUsersRouteImport } from './routes/admin/_gated/users'
import { Route as AdminGatedSupportRouteImport } from './routes/admin/_gated/support'
import { Route as AdminGatedSitesRouteImport } from './routes/admin/_gated/sites'
import { Route as AdminGatedSettingsRouteImport } from './routes/admin/_gated/settings'
import { Route as AdminGatedSearchRouteImport } from './routes/admin/_gated/search'
import { Route as AdminGatedReportsRouteImport } from './routes/admin/_gated/reports'
import { Route as AdminGatedPaymentsRouteImport } from './routes/admin/_gated/payments'
import { Route as AdminGatedNotificationsRouteImport } from './routes/admin/_gated/notifications'
import { Route as AdminGatedDashboardRouteImport } from './routes/admin/_gated/dashboard'
import { Route as AdminGatedCmsRouteImport } from './routes/admin/_gated/cms'
import { Route as AdminGatedAuditRouteImport } from './routes/admin/_gated/audit'
import { Route as AuthenticatedDashboardSitesRouteImport } from './routes/_authenticated/dashboard.sites'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedDashboardPaymentsRouteImport } from './routes/_authenticated/dashboard.payments'
import { Route as AuthenticatedDashboardAnalyticsRouteImport } from './routes/_authenticated/dashboard.analytics'
import { Route as AuthenticatedDashboardAdUnitsRouteImport } from './routes/_authenticated/dashboard.ad-units'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as AdminGatedUsersUserIdRouteImport } from './routes/admin/_gated/users.$userId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminGatedRouteRoute = AdminGatedRouteRouteImport.update({
  id: '/_gated',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AdminGatedUsersRoute = AdminGatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminGatedRouteRoute,
} as any)
const AdminGatedSupportRoute = AdminGatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminGatedRouteRoute,
} as any)
const AdminGatedSitesRoute = AdminGatedSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AdminGatedRouteRoute,
} as any)
const AdminGatedSettingsRoute = AdminGatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminGatedRouteRoute,
} as any)
const AdminGatedSearchRoute = AdminGatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AdminGatedRouteRoute,
} as any)
const AdminGatedReportsRoute = AdminGatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminGatedRouteRoute,
} as any)
const AdminGatedPaymentsRoute = AdminGatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminGatedRouteRoute,
} as any)
const AdminGatedNotificationsRoute = AdminGatedNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminGatedRouteRoute,
} as any)
const AdminGatedDashboardRoute = AdminGatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminGatedRouteRoute,
} as any)
const AdminGatedCmsRoute = AdminGatedCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminGatedRouteRoute,
} as any)
const AdminGatedAuditRoute = AdminGatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminGatedRouteRoute,
} as any)
const AuthenticatedDashboardSitesRoute =
  AuthenticatedDashboardSitesRouteImport.update({
    id: '/sites',
    path: '/sites',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPaymentsRoute =
  AuthenticatedDashboardPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAnalyticsRoute =
  AuthenticatedDashboardAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdUnitsRoute =
  AuthenticatedDashboardAdUnitsRouteImport.update({
    id: '/ad-units',
    path: '/ad-units',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGatedUsersUserIdRoute = AdminGatedUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminGatedUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/ad-units': typeof AuthenticatedDashboardAdUnitsRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/payments': typeof AuthenticatedDashboardPaymentsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/sites': typeof AuthenticatedDashboardSitesRoute
  '/admin/audit': typeof AdminGatedAuditRoute
  '/admin/cms': typeof AdminGatedCmsRoute
  '/admin/dashboard': typeof AdminGatedDashboardRoute
  '/admin/notifications': typeof AdminGatedNotificationsRoute
  '/admin/payments': typeof AdminGatedPaymentsRoute
  '/admin/reports': typeof AdminGatedReportsRoute
  '/admin/search': typeof AdminGatedSearchRoute
  '/admin/settings': typeof AdminGatedSettingsRoute
  '/admin/sites': typeof AdminGatedSitesRoute
  '/admin/support': typeof AdminGatedSupportRoute
  '/admin/users': typeof AdminGatedUsersRouteWithChildren
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/admin/users/$userId': typeof AdminGatedUsersUserIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AdminIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/dashboard/ad-units': typeof AuthenticatedDashboardAdUnitsRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/payments': typeof AuthenticatedDashboardPaymentsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/sites': typeof AuthenticatedDashboardSitesRoute
  '/admin/audit': typeof AdminGatedAuditRoute
  '/admin/cms': typeof AdminGatedCmsRoute
  '/admin/dashboard': typeof AdminGatedDashboardRoute
  '/admin/notifications': typeof AdminGatedNotificationsRoute
  '/admin/payments': typeof AdminGatedPaymentsRoute
  '/admin/reports': typeof AdminGatedReportsRoute
  '/admin/search': typeof AdminGatedSearchRoute
  '/admin/settings': typeof AdminGatedSettingsRoute
  '/admin/sites': typeof AdminGatedSitesRoute
  '/admin/support': typeof AdminGatedSupportRoute
  '/admin/users': typeof AdminGatedUsersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/admin/users/$userId': typeof AdminGatedUsersUserIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/_gated': typeof AdminGatedRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/dashboard/ad-units': typeof AuthenticatedDashboardAdUnitsRoute
  '/_authenticated/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/_authenticated/dashboard/payments': typeof AuthenticatedDashboardPaymentsRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/sites': typeof AuthenticatedDashboardSitesRoute
  '/admin/_gated/audit': typeof AdminGatedAuditRoute
  '/admin/_gated/cms': typeof AdminGatedCmsRoute
  '/admin/_gated/dashboard': typeof AdminGatedDashboardRoute
  '/admin/_gated/notifications': typeof AdminGatedNotificationsRoute
  '/admin/_gated/payments': typeof AdminGatedPaymentsRoute
  '/admin/_gated/reports': typeof AdminGatedReportsRoute
  '/admin/_gated/search': typeof AdminGatedSearchRoute
  '/admin/_gated/settings': typeof AdminGatedSettingsRoute
  '/admin/_gated/sites': typeof AdminGatedSitesRoute
  '/admin/_gated/support': typeof AdminGatedSupportRoute
  '/admin/_gated/users': typeof AdminGatedUsersRouteWithChildren
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/admin/_gated/users/$userId': typeof AdminGatedUsersUserIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/dashboard'
    | '/admin/login'
    | '/admin/'
    | '/dashboard/ad-units'
    | '/dashboard/analytics'
    | '/dashboard/payments'
    | '/dashboard/settings'
    | '/dashboard/sites'
    | '/admin/audit'
    | '/admin/cms'
    | '/admin/dashboard'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/sites'
    | '/admin/support'
    | '/admin/users'
    | '/dashboard/'
    | '/admin/users/$userId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/admin'
    | '/admin/login'
    | '/dashboard/ad-units'
    | '/dashboard/analytics'
    | '/dashboard/payments'
    | '/dashboard/settings'
    | '/dashboard/sites'
    | '/admin/audit'
    | '/admin/cms'
    | '/admin/dashboard'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/sites'
    | '/admin/support'
    | '/admin/users'
    | '/dashboard'
    | '/admin/users/$userId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/about'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/admin/_gated'
    | '/_authenticated/dashboard'
    | '/admin/login'
    | '/admin/'
    | '/_authenticated/dashboard/ad-units'
    | '/_authenticated/dashboard/analytics'
    | '/_authenticated/dashboard/payments'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/sites'
    | '/admin/_gated/audit'
    | '/admin/_gated/cms'
    | '/admin/_gated/dashboard'
    | '/admin/_gated/notifications'
    | '/admin/_gated/payments'
    | '/admin/_gated/reports'
    | '/admin/_gated/search'
    | '/admin/_gated/settings'
    | '/admin/_gated/sites'
    | '/admin/_gated/support'
    | '/admin/_gated/users'
    | '/_authenticated/dashboard/'
    | '/admin/_gated/users/$userId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/_gated': {
      id: '/admin/_gated'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminGatedRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/admin/_gated/users': {
      id: '/admin/_gated/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminGatedUsersRouteImport
      parentRoute: typeof AdminGatedRouteRoute
    }
    '/admin/_gated/support': {
      id: '/admin/_gated/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminGatedSupportRouteImport
      parentRoute: typeof AdminGatedRouteRoute
    }
    '/admin/_gated/sites': {
      id: '/admin/_gated/sites'
      path: '/sites'
      fullPath: '/admin/sites'
      preLoaderRoute: typeof AdminGatedSitesRouteImport
      parentRoute: typeof AdminGatedRouteRoute
    }
    '/admin/_gated/settings': {
      id: '/admin/_gated/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminGatedSettingsRouteImport
      parentRoute: typeof AdminGatedRouteRoute
    }
    '/admin/_gated/search': {
      id: '/admin/_gated/search'
      path: '/search'
      fullPath: '/admin/search'
      preLoaderRoute: typeof AdminGatedSearchRouteImport
      parentRoute: typeof AdminGatedRouteRoute
    }
    '/admin/_gated/reports': {
      id: '/admin/_gated/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminGatedReportsRouteImport
      parentRoute: typeof AdminGatedRouteRoute
    }
    '/admin/_gated/payments': {
      id: '/admin/_gated/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminGatedPaymentsRouteImport
      parentRoute: typeof AdminGatedRouteRoute
    }
    '/admin/_gated/notifications': {
      id: '/admin/_gated/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminGatedNotificationsRouteImport
      parentRoute: typeof AdminGatedRouteRoute
    }
    '/admin/_gated/dashboard': {
      id: '/admin/_gated/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminGatedDashboardRouteImport
      parentRoute: typeof AdminGatedRouteRoute
    }
    '/admin/_gated/cms': {
      id: '/admin/_gated/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminGatedCmsRouteImport
      parentRoute: typeof AdminGatedRouteRoute
    }
    '/admin/_gated/audit': {
      id: '/admin/_gated/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminGatedAuditRouteImport
      parentRoute: typeof AdminGatedRouteRoute
    }
    '/_authenticated/dashboard/sites': {
      id: '/_authenticated/dashboard/sites'
      path: '/sites'
      fullPath: '/dashboard/sites'
      preLoaderRoute: typeof AuthenticatedDashboardSitesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/payments': {
      id: '/_authenticated/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof AuthenticatedDashboardPaymentsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/analytics': {
      id: '/_authenticated/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof AuthenticatedDashboardAnalyticsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/ad-units': {
      id: '/_authenticated/dashboard/ad-units'
      path: '/ad-units'
      fullPath: '/dashboard/ad-units'
      preLoaderRoute: typeof AuthenticatedDashboardAdUnitsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_gated/users/$userId': {
      id: '/admin/_gated/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminGatedUsersUserIdRouteImport
      parentRoute: typeof AdminGatedUsersRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAdUnitsRoute: typeof AuthenticatedDashboardAdUnitsRoute
  AuthenticatedDashboardAnalyticsRoute: typeof AuthenticatedDashboardAnalyticsRoute
  AuthenticatedDashboardPaymentsRoute: typeof AuthenticatedDashboardPaymentsRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardSitesRoute: typeof AuthenticatedDashboardSitesRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAdUnitsRoute: AuthenticatedDashboardAdUnitsRoute,
    AuthenticatedDashboardAnalyticsRoute: AuthenticatedDashboardAnalyticsRoute,
    AuthenticatedDashboardPaymentsRoute: AuthenticatedDashboardPaymentsRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardSitesRoute: AuthenticatedDashboardSitesRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminGatedUsersRouteChildren {
  AdminGatedUsersUserIdRoute: typeof AdminGatedUsersUserIdRoute
}

const AdminGatedUsersRouteChildren: AdminGatedUsersRouteChildren = {
  AdminGatedUsersUserIdRoute: AdminGatedUsersUserIdRoute,
}

const AdminGatedUsersRouteWithChildren = AdminGatedUsersRoute._addFileChildren(
  AdminGatedUsersRouteChildren,
)

interface AdminGatedRouteRouteChildren {
  AdminGatedAuditRoute: typeof AdminGatedAuditRoute
  AdminGatedCmsRoute: typeof AdminGatedCmsRoute
  AdminGatedDashboardRoute: typeof AdminGatedDashboardRoute
  AdminGatedNotificationsRoute: typeof AdminGatedNotificationsRoute
  AdminGatedPaymentsRoute: typeof AdminGatedPaymentsRoute
  AdminGatedReportsRoute: typeof AdminGatedReportsRoute
  AdminGatedSearchRoute: typeof AdminGatedSearchRoute
  AdminGatedSettingsRoute: typeof AdminGatedSettingsRoute
  AdminGatedSitesRoute: typeof AdminGatedSitesRoute
  AdminGatedSupportRoute: typeof AdminGatedSupportRoute
  AdminGatedUsersRoute: typeof AdminGatedUsersRouteWithChildren
}

const AdminGatedRouteRouteChildren: AdminGatedRouteRouteChildren = {
  AdminGatedAuditRoute: AdminGatedAuditRoute,
  AdminGatedCmsRoute: AdminGatedCmsRoute,
  AdminGatedDashboardRoute: AdminGatedDashboardRoute,
  AdminGatedNotificationsRoute: AdminGatedNotificationsRoute,
  AdminGatedPaymentsRoute: AdminGatedPaymentsRoute,
  AdminGatedReportsRoute: AdminGatedReportsRoute,
  AdminGatedSearchRoute: AdminGatedSearchRoute,
  AdminGatedSettingsRoute: AdminGatedSettingsRoute,
  AdminGatedSitesRoute: AdminGatedSitesRoute,
  AdminGatedSupportRoute: AdminGatedSupportRoute,
  AdminGatedUsersRoute: AdminGatedUsersRouteWithChildren,
}

const AdminGatedRouteRouteWithChildren = AdminGatedRouteRoute._addFileChildren(
  AdminGatedRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminGatedRouteRoute: typeof AdminGatedRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminGatedRouteRoute: AdminGatedRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
